version: "3.8"

services:
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules/

  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    env_file:
      - .env
